### ISSUE TITLE
Error in starting gbuild

### ISSUE THREAD

**Issue by paulwoelfel** [matti/gbuild#1]
Hi, I tried to run gbuild, but it fails:

```
$ gbuild gcr.io/cp-paul-test/apache
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:860:in `block in result': no implicit conversion of Hash intoInteger (TypeError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:862:in `result'
        from /Library/Ruby/Gems/2.3.0/gems/gbuild-0.2.0/lib/gbuild/template.rb:16:in `result'
        from /Library/Ruby/Gems/2.3.0/gems/gbuild-0.2.0/lib/gbuild/build_command.rb:39:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/gbuild-0.2.0/lib/gbuild/root_command.rb:29:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/gbuild-0.2.0/exe/gbuild:12:in `<top (required)>'
        from /usr/local/bin/gbuild:22:in `load'
        from /usr/local/bin/gbuild:22:in `<main>'
```

I'm running OSX 10.14.12. I've installed gbuild with `sudo gem install gbuild`.

```
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

**Comment by matti** [comment]
Thanks, I was able to reproduce this with your Ruby version - it works with 2.6.0 - I'll dig in and see what's up.

Meanwhile can you try binaries https://github.com/matti/gbuild/releases ?

**Comment by matti** [comment]
Fixed in https://github.com/matti/gbuild/commit/56e1c254d8a4b8b283fc59e7576804068c999d17#diff-793e938e6dbbee5654c3c01936fcbd10R8

Gem 0.3.1 should be out soon after travis finishes it's build.

Ruby 2.6.0 had a breaking change and I only tested with 2.6.0 ...
